[package]
name = "charinfo"
version = "0.1.0"
authors = ["<ogham@bsago.me>"]

[[bin]]
name = "charinfo"

[dependencies]
ansi_term = "*"
getopts = "*"
unicode_names = "*"
unicode-width = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
